#ifndef _COLORS_H
#define _COLORS_H

#include "inttype.h"

enum vga_color {
	VGA_COLOR_BLACK = 0,
	VGA_COLOR_BLUE = 1,
	VGA_COLOR_GREEN = 2,
	VGA_COLOR_CYAN = 3,
	VGA_COLOR_RED = 4,
	VGA_COLOR_MAGENTA = 5,
	VGA_COLOR_BROWN = 6,
	VGA_COLOR_LIGHT_GREY = 7,
	VGA_COLOR_DARK_GREY = 8,
	VGA_COLOR_LIGHT_BLUE = 9,
	VGA_COLOR_LIGHT_GREEN = 10,
	VGA_COLOR_LIGHT_CYAN = 11,
	VGA_COLOR_LIGHT_RED = 12,
	VGA_COLOR_LIGHT_MAGENTA = 13,
	VGA_COLOR_LIGHT_BROWN = 14,
	VGA_COLOR_WHITE = 15,
};

/**
 * @brief Predefined VGA color profiles to choose from
 */
enum vga_color_profile {
	VGA_MODE_GREEN_ON_BLACK = 0x02, //HACKY
    VGA_MODE_WHITE_ON_BLACK = 0x0F, //ARRRGH
    VGA_MODE_BLACK_ON_WHITE = 0xF0, //BORING
    VGA_MODE_BLACK_ON_RED = 0x40, //DANGER
    VGA_MODE_BLUE_ON_CYAN = 0x31 //VERY_IMPORTANT
};

#endif /* _COLORS_H */